### ISSUE TITLE
Assignment 3 Fibonacci Sequence Generator

### ISSUE THREAD

**Issue by 53bit23** [vtcbca/basic-programming-53bit23#2]
i did not understand the problem

**Comment by 55bit23** [comment]
The Fibonacci sequence is a list of numbers where each number is the sum of the two numbers before it.

**Comment by 51bit23** [comment]
I am also finding the asnwer of this problem.

**Comment by 55bit23** [comment]
The Fibonacci sequence is a list of numbers where each number is the sum of the two numbers before it.

**Comment by 53bit23** [comment]
@55bit23  can you explain it by giving the example ?

**Comment by 55bit23** [comment]
Start with 0 and 1, add the last two numbers to get the next one: 0 + 1 = 1, 1 + 1 = 2, 1 + 2 = 3, 2 + 3 = 5, 3 + 5 = 8, and so on.

**Comment by 51bit23** [comment]
ok got it .

**Comment by 55bit23** [comment]
@53bit23 are you getting me?

**Comment by 53bit23** [comment]
yes!
