### ISSUE TITLE
Factorial Calculator Calculate the factorial  Assignment 1:

### ISSUE THREAD

**Issue by 53bit23** [vtcbca/basic-programming-53bit23#3]
What method i can use to solve this program ?

**Comment by 44bit23** [comment]
There Are multiple ways to solve this program!

**Comment by 53bit23** [comment]
Can you tell me a specific method to solve it?

**Comment by 44bit23** [comment]
using for loop method

**Comment by 53bit23** [comment]
Tell me in detail.

**Comment by 44bit23** [comment]
You have to start the loop from 1 to the given number, multiply every number, then calculate and print the sum of all those numbers.

**Comment by 53bit23** [comment]
Okay, got it now I can solve my problem easily

**Comment by 44bit23** [comment]
Great!
