### ISSUE TITLE
 Assignment-2:  Prime Number Checker

### ISSUE THREAD

**Issue by 53bit23** [vtcbca/basic-programming-53bit23#4]
Can someone help me in this program?

**Comment by 62bit23** [comment]
it is a program about Prime Number Checker

**Comment by 53bit23** [comment]
What is a prime number?

**Comment by 62bit23** [comment]
A prime number is a natural number greater than 1 that has no divisors other than 1 and itself.
Examples: 2, 3, 5, 7, 11, etc.

**Comment by 53bit23** [comment]
What is the smallest prime number?

**Comment by 62bit23** [comment]
The smallest prime number is 2.

**Comment by 53bit23** [comment]
Is 1 a prime number?

**Comment by 62bit23** [comment]
No, 1 is not a prime number because it has only one divisor (itself), while a prime number requires exactly two divisors.

**Comment by 53bit23** [comment]
how can I store  prime number in my program?

**Comment by 62bit23** [comment]
To store prime numbers in your program, you can use a list in Python. You can either manually add primes to the list or write a program to find and store them dynamically.

**Comment by 53bit23** [comment]
Okey thanks for helping me  @53bit23 .
