### ISSUE TITLE
Assignment-4 : Reverse String Enter string and print it in reverse.

### ISSUE THREAD

**Issue by 63bit23** [vtcbca/basic-programming-53bit23#5]
What is a string in  python programming?

**Comment by 53bit23** [comment]
A string is a collection of characters, like words, sentences, or even numbers, written in quotes.

**Comment by 63bit23** [comment]
How  can  I  implement string in python?

**Comment by 53bit23** [comment]
ou can implement a string in Python by defining it with either single quotes ('), double quotes ("), or triple quotes (''' or """) for multiline strings.

**Comment by 63bit23** [comment]
What is meant by reversing a string?

**Comment by 53bit23** [comment]
Reversing a string means writing its characters in the opposite order. For example, "Python" becomes "nohtyP".

**Comment by 63bit23** [comment]
What data type is used for storing strings in Python?

**Comment by 53bit23** [comment]
Strings are stored as the str data type in Python.

**Comment by 53bit23** [comment]
ok
